export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const SET_NOTEBOOKS_LOCATION = 'SET_NOTEBOOKS_LOCATION';
export type SET_NOTEBOOKS_LOCATION = typeof SET_NOTEBOOKS_LOCATION;

export const ADD_NOTEBOOK = 'ADD_NOTEBOOK';
export type ADD_NOTEBOOK = typeof ADD_NOTEBOOK;

export const NOTEBOOK_SAVE_DIRECTORY = 'NOTEBOOK_SAVE_DIRECTORY';
export type NOTEBOOK_SAVE_DIRECTORY = typeof NOTEBOOK_SAVE_DIRECTORY;

export const CHOOSE_LOCATION_FOR_NOTEBOOKS = 'CHOOSE_LOCATION_FOR_NOTEBOOKS';
export type CHOOSE_LOCATION_FOR_NOTEBOOKS = typeof CHOOSE_LOCATION_FOR_NOTEBOOKS;