export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const SET_NOTEBOOKS_LOCATION = 'SET_NOTEBOOKS_LOCATION';
export type SET_NOTEBOOKS_LOCATION = typeof SET_NOTEBOOKS_LOCATION;

export const ADD_NOTEBOOK = 'ADD_NOTEBOOK';
export type ADD_NOTEBOOK = typeof ADD_NOTEBOOK;

export const NOTEBOOK_SAVE_DIRECTORY = 'NOTEBOOK_SAVE_DIRECTORY';
export type NOTEBOOK_SAVE_DIRECTORY = typeof NOTEBOOK_SAVE_DIRECTORY;

export const CHOOSE_LOCATION_FOR_NOTEBOOKS = 'CHOOSE_LOCATION_FOR_NOTEBOOKS';
export type CHOOSE_LOCATION_FOR_NOTEBOOKS = typeof CHOOSE_LOCATION_FOR_NOTEBOOKS;

export const GET_NOTEBOOKS = 'GET_NOTEBOOKS';
export type GET_NOTEBOOKS = typeof GET_NOTEBOOKS;

export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export type LOAD_SETTINGS = typeof LOAD_SETTINGS;

export const ADD_NOTE = 'ADD_NOTE';
export type ADD_NOTE = typeof ADD_NOTE;

export const GET_NOTES = 'GET_NOTES';
export type GET_NOTES = typeof GET_NOTES;

export const LOAD_NOTES = 'LOAD_NOTES';
export type LOAD_NOTES = typeof LOAD_NOTES;

export const UPDATE_NOTE_STATE = 'UPDATE_NOTE_STATE';
export type UPDATE_NOTE_STATE = typeof UPDATE_NOTE_STATE;

export const LAST_OPENED_NOTE = 'LAST_OPENED_NOTE';
export type LAST_OPENED_NOTE = typeof LAST_OPENED_NOTE;

export const UPDATE_NOTE = 'UPDATE_NOTE';
export type UPDATE_NOTE = typeof UPDATE_NOTE;

export const LOAD_CONTENT_INTO_NOTE = 'LOAD_CONTENT_INTO_NOTE';
export type LOAD_CONTENT_INTO_NOTE = typeof LOAD_CONTENT_INTO_NOTE;

export const GET_NAME_OF_LAST_OPENED_NOTE = 'GET_NAME_OF_LAST_OPENED_NOTE';
export type GET_NAME_OF_LAST_OPENED_NOTE = typeof GET_NAME_OF_LAST_OPENED_NOTE;

export const GET_NOTE_CONTENT = 'GET_NOTE_CONTENT';
export type GET_NOTE_CONTENT = typeof GET_NOTE_CONTENT;

export const DELETE_NOTE = 'DELETE_NOTE';
export type DELETE_NOTE = typeof DELETE_NOTE;

export const GET_TRASH = 'GET_TRASH';
export type GET_TRASH = typeof GET_TRASH;

export const LOAD_TRASH = 'LOAD_TRASH';
export type LOAD_TRASH = typeof LOAD_TRASH;

export const GET_NOTE_FROM_TRASH = 'GET_NOTE_FROM_TRASH';
export type GET_NOTE_FROM_TRASH = typeof GET_NOTE_FROM_TRASH;

export const LOAD_LAST_OPENED_TRASH_NOTE = 'LOAD_LAST_OPENED_TRASH_NOTE';
export type LOAD_LAST_OPENED_TRASH_NOTE = typeof LOAD_LAST_OPENED_TRASH_NOTE;

export const LOAD_LAST_OPENED_TRASH_NOTEBOOK = 'LOAD_LAST_OPENED_TRASH_NOTEBOOK';
export type LOAD_LAST_OPENED_TRASH_NOTEBOOK = typeof LOAD_LAST_OPENED_TRASH_NOTEBOOK;

export const RESTORE_NOTE_FROM_TRASH = 'RESTORE_NOTE_FROM_TRASH';
export type RESTORE_NOTE_FROM_TRASH = typeof RESTORE_NOTE_FROM_TRASH;

export const EXIT_APP_SAVE_CONTENT = 'EXIT_APP_SAVE_CONTENT';
export type EXIT_APP_SAVE_CONTENT = typeof EXIT_APP_SAVE_CONTENT;

export const ADD_TAG_TO_NOTE = 'ADD_TAG_TO_NOTE';
export type ADD_TAG_TO_NOTE = typeof ADD_TAG_TO_NOTE;

export const REMOVE_TAG_FROM_NOTE = 'REMOVE_TAG_FROM_NOTE';
export type REMOVE_TAG_FROM_NOTE = typeof REMOVE_TAG_FROM_NOTE;

export const GET_TAGS_FOR_NOTE = 'GET_TAGS_FOR_NOTE';
export type GET_TAGS_FOR_NOTE = typeof GET_TAGS_FOR_NOTE;

export const LOAD_TAGS_FOR_NOTE = 'LOAD_TAGS_FOR_NOTE';
export type LOAD_TAGS_FOR_NOTE = typeof LOAD_TAGS_FOR_NOTE;

export const REMOVE_NOTE_FROM_DRIVE = 'REMOVE_NOTE_FROM_DRIVE';
export type REMOVE_NOTE_FROM_DRIVE = typeof REMOVE_NOTE_FROM_DRIVE;

export const GLOBAL_SEARCH = 'GLOBAL_SEARCH';
export type GLOBAL_SEARCH = typeof GLOBAL_SEARCH;

export const SEARCH_RESULTS = 'SEARCH_RESULTS';
export type SEARCH_RESULTS = typeof SEARCH_RESULTS;

export const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS';
export type LOAD_SEARCH_RESULTS = typeof LOAD_SEARCH_RESULTS;

export const SEARCH_WITHIN_NOTEBOOK = 'SEARCH_WITHIN_NOTEBOOK';
export type SEARCH_WITHIN_NOTEBOOK = typeof SEARCH_WITHIN_NOTEBOOK;

export const PREVIEW_NOTE = 'PREVIEW_NOTE';
export type PREVIEW_NOTE = typeof PREVIEW_NOTE;

export const LOAD_PREVIEW_CONTENT = 'LOAD_PREVIEW_CONTENT';
export type LOAD_PREVIEW_CONTENT = typeof LOAD_PREVIEW_CONTENT;

export const UPDATE_PREVIEW_CONTENT_TAGS = 'UPDATE_PREVIEW_CONTENT_TAGS';
export type UPDATE_PREVIEW_CONTENT_TAGS = typeof UPDATE_PREVIEW_CONTENT_TAGS;