export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const SET_NOTEBOOKS_LOCATION = 'SET_NOTEBOOKS_LOCATION';
export type SET_NOTEBOOKS_LOCATION = typeof SET_NOTEBOOKS_LOCATION;

export const ADD_NOTEBOOK = 'ADD_NOTEBOOK';
export type ADD_NOTEBOOK = typeof ADD_NOTEBOOK;

export const NOTEBOOK_SAVE_DIRECTORY = 'NOTEBOOK_SAVE_DIRECTORY';
export type NOTEBOOK_SAVE_DIRECTORY = typeof NOTEBOOK_SAVE_DIRECTORY;

export const CHOOSE_LOCATION_FOR_NOTEBOOKS = 'CHOOSE_LOCATION_FOR_NOTEBOOKS';
export type CHOOSE_LOCATION_FOR_NOTEBOOKS = typeof CHOOSE_LOCATION_FOR_NOTEBOOKS;

export const GET_NOTEBOOKS = 'GET_NOTEBOOKS';
export type GET_NOTEBOOKS = typeof GET_NOTEBOOKS;

export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export type LOAD_SETTINGS = typeof LOAD_SETTINGS;

export const ADD_NOTE = 'ADD_NOTE';
export type ADD_NOTE = typeof ADD_NOTE;

export const GET_NOTES = 'GET_NOTES';
export type GET_NOTES = typeof GET_NOTES;

export const LOAD_NOTES = 'LOAD_NOTES';
export type LOAD_NOTES = typeof LOAD_NOTES;

export const UPDATE_NOTE_STATE = 'UPDATE_NOTE_STATE';
export type UPDATE_NOTE_STATE = typeof UPDATE_NOTE_STATE;

export const LAST_OPENED_NOTE = 'LAST_OPENED_NOTE';
export type LAST_OPENED_NOTE = typeof LAST_OPENED_NOTE;

export const UPDATE_NOTE = 'UPDATE_NOTE';
export type UPDATE_NOTE = typeof UPDATE_NOTE;