"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
exports.DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
exports.SET_NOTEBOOKS_LOCATION = 'SET_NOTEBOOKS_LOCATION';
exports.ADD_NOTEBOOK = 'ADD_NOTEBOOK';
exports.NOTEBOOK_SAVE_DIRECTORY = 'NOTEBOOK_SAVE_DIRECTORY';
exports.CHOOSE_LOCATION_FOR_NOTEBOOKS = 'CHOOSE_LOCATION_FOR_NOTEBOOKS';
