export const NOTEBOOK_SAVE_DIRECTORY = 'NOTEBOOK_SAVE_DIRECTORY';
export const CHOOSE_LOCATION_FOR_NOTEBOOKS = 'CHOOSE_LOCATION_FOR_NOTEBOOKS';
export const GET_NOTEBOOKS = 'GET_NOTEBOOKS';
export const NOTEBOOKS = 'NOTEBOOKS';